=== yearn/yearn-meta/schema/token.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "token.json",
  "title": "Token",
  "description": "An underlying token of a Yearn vault",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "website": {
      "type": "string"
    },
    "tokenIconOverride": {
      "type": "string"
    },
    "tokenSymbolOverride": {
      "type": "string"
    },
    "tokenNameOverride": {
      "type": "string"
    },
    "supportedZaps": {
      "type": "object",
      "properties": {
        "ftmApeZap": {
          "type": "boolean"
        }
      }
    }
  },
  "required": []
}

=== yearn/yearn-meta/data/tokens/1/0x194eBd173F6cDacE046C53eACcE9B953F28411d1.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains EURS and synthetic euro (sEUR) minted on the Synthetix platform.",
  "website": "https://www.curve.fi/eurs/",
  "tokenSymbolOverride": "crvEURS",
  "tokenNameOverride": "Curve EURS Pool"
}

=== yearn/yearn-meta/data/tokens/1/0x6BA5b4e438FA0aAf7C1bD179285aF65d13bD3D90.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This metapool contains 3Crv (DAI, USDC, and USDT) and RAI. Please be aware that as RAI is not pegged to $1, this pool may be subject to impermanent loss.",
  "website": "https://curve.fi/rai",
  "tokenSymbolOverride": "crvRAI",
  "tokenNameOverride": "Curve RAI+3Crv Pool"
}

=== yearn/yearn-meta/data/tokens/1/0xEcd5e75AFb02eFa118AF914515D6521aaBd189F1.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This factory metapool contains 3Crv (DAI, USDC, and USDT) and TrueUSD.",
  "website": "https://www.curve.fi/tusd/",
  "tokenSymbolOverride": "crvTUSD",
  "tokenNameOverride": "Curve TUSD Pool"
}
