=== yearn/yearn-meta/schema/token.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "token.json",
  "title": "Token",
  "description": "An underlying token of a Yearn vault",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "website": {
      "type": "string"
    },
    "tokenIconOverride": {
      "type": "string"
    },
    "tokenSymbolOverride": {
      "type": "string"
    },
    "tokenNameOverride": {
      "type": "string"
    },
    "supportedZaps": {
      "type": "object",
      "properties": {
        "ftmApeZap": {
          "type": "boolean"
        }
      }
    }
  },
  "required": []
}

=== yearn/yearn-meta/data/tokens/1/0x9c2C8910F113181783c249d8F6Aa41b51Cde0f0c.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains ibCHF, a synthetic Swiss franc minted from the Iron Bank, and synthetic Swiss franc (sCHF) minted on the Synthetix platform.",
  "website": "https://curve.fi/factory/31",
  "tokenSymbolOverride": "crvIBCHF",
  "tokenNameOverride": "Curve ibCHF Pool"
}

=== yearn/yearn-meta/data/tokens/1/0xC25a3A3b969415c80451098fa907EC722572917F.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, USDT, and synthetic USD (sUSD) minted on the Synthetix platform. ",
  "website": "https://www.curve.fi/susdv2/",
  "tokenSymbolOverride": "crvSUSD",
  "tokenNameOverride": "Curve sUSD Pool"
}

=== yearn/yearn-meta/data/tokens/1/0xAA5A67c256e27A5d80712c51971408db3370927D.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This metapool contains 3Crv (DAI, USDC, and USDT) and DOLA, a synthetic USD stablecoin that can be minted by using other assets on Inverse Finance (https://www.inverse.finance) as collateral.",
  "website": "https://curve.fi",
  "tokenSymbolOverride": "crvDOLA",
  "tokenNameOverride": "Curve DOLA Pool"
}

=== yearn/yearn-meta/data/tokens/1/0x4807862AA8b2bF68830e4C8dc86D0e9A998e085a.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This factory metapool contains 3Crv (DAI, USDC, and USDT) and Binance USD, a regulated stablecoin issued by Paxos.",
  "website": "https://curve.fi/busdv2",
  "tokenSymbolOverride": "crvBUSD",
  "tokenNameOverride": "Curve BUSD Pool"
}

=== yearn/yearn-meta/data/tokens/1/0x19b080FE1ffA0553469D20Ca36219F17Fcf03859.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains ibEUR, a synthetic euro minted from the Iron Bank, and synthetic euro (sEUR) minted on the Synthetix platform.",
  "website": "https://curve.fi/factory/3/",
  "tokenSymbolOverride": "crvIBEUR",
  "tokenNameOverride": "Curve ibEUR Pool"
}

=== yearn/yearn-meta/data/tokens/1/0x06325440D014e39736583c165C2963BA99fAf14E.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains ETH and stETH, a token that represents staked ether in Lido, a decentralized ETH 2.0 staking platform.",
  "website": "https://www.curve.fi/steth/",
  "tokenSymbolOverride": "crvSTETH",
  "tokenNameOverride": "Curve stETH Pool"
}

=== yearn/yearn-meta/data/tokens/1/0xcA3d75aC011BF5aD07a98d02f18225F9bD9A6BDF.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This crypto pool contains USDT, WBTC, and WETH. Please be aware that as crypto pools are composed of differently-priced assets, they are subject to impermanent loss.",
  "website": "https://curve.fi/tricrypto2",
  "tokenSymbolOverride": "crvTricrypto",
  "tokenNameOverride": "Curve triCrypto Pool"
}

=== yearn/yearn-meta/data/tokens/250/0xd02a30d33153877bc20e5721ee53dedee0422b2f.json
{
  "$schema": "token",
  "categories": ["Curve LP Tokens"],
  "description": "This token represents a Curve liquidity pool. Holders earn fees from users trading in the pool, and can also deposit the LP to Curve's gauges to earn CRV emissions. This pool contains DAI, USDC, and USDT that are lent out to Geist, a decentralized money market on Ethereum.",
  "website": "https://curve.fi",
  "tokenSymbolOverride": "crvGEIST",
  "tokenNameOverride": "Curve Geist Pool"
}
